name: lbrydart
description: LBRY API binding for the Dart Programming language
version: 0.1.0
author: Oleg Silkin <o.silkin98@gmail.com>
homepage: https://github.com/osilkin98/LBRYDart
documentation:
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: any


