name: lbry_api
description: >-
  LBRY API binding for the Dart language.
  Use this library in order to make API calls to the
  lbry network as its running in the background.

version: 0.1.6
author: Oleg Silkin <o.silkin98@gmail.com>
homepage: https://github.com/osilkin98/LBRYDart
documentation:
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http:  ^0.12.0


