name: lbry
description: >-
  LBRY API binding for the Dart Programming language.
  Use this library in order to make API calls to the
  LBRY daemon as its running in the background.
  Currently Supports both lbryd and lbrycrd.

version: 0.1.2
author: Oleg Silkin <o.silkin98@gmail.com>
homepage: https://github.com/osilkin98/LBRYDart
documentation:
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http:  ^0.12.0


